uap/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'uap.views.home', name='home'),
    # url(r'^uap/', include('uap.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
     url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
    
    #REDIRECTS
    url(r'^no_access/$', 'uap_app.views.no_access' ),
    
    #BASIC
    #url(r'^tutee/upload_test/$', 'uap_app.views.upload_handler'),
    url(r'^$', 'uap_app.views.basecase_home' ),
    url(r'^tutee/signup/$', 'uap_app.views.basecase_signup_tutee' ),
    url(r'^coach/request/$', 'uap_app.views.basecase_coach_application' ),
    url(r'^tutee/agreement/$', 'uap_app.views.tutee_agreement' ),
    url(r'^tutee_agreement/$', 'uap_app.views.view_tutee_agreement' ),
    url(r'^contact/', 'uap_app.views.basecase_contact'),
    url(r'^tutee/signup/validate$', 'uap_app.views.tutee_signup' ),
    url(r'^accounts/login/$', 'uap_app.views.logging_in' ),
    url(r'^logout$', 'uap_app.views.logging_out' ),
    url(r'^login/pw_request/$', 'uap_app.views.pw_request' ),
    
    #TUTEE
    url(r'^tutee/ticket_(?P<pid>\d+)/cancel/$', 'uap_app.views.cancel_ticket' ),
    url(r'^tutee/ticket_(?P<pid>\d+)/confirm/$', 'uap_app.views.confirm_ticket' ),
    url(r'^tutee/ticket_(?P<pid>\d+)/reject/$', 'uap_app.views.reject_ticket' ),
    url(r'^tutee/new_ticket/$', 'uap_app.views.new_project' ),
    url(r'^tutee/profile/$', 'uap_app.views.tutee_profile' ),
    url(r'^tutee/home/$', 'uap_app.views.home_tutee' ),
    url(r'^home/failure$', 'uap_app.views.home_failure' ),
    url(r'^tutee/tickets/$', 'uap_app.views.all_requests_tutee' ),
    url(r'^tutee/ticket_(?P<pid>\d+)$', 'uap_app.views.project_tutee' ),
    url(r'^tutee/report/$', 'uap_app.views.report_tutee'),
    
    #COACH
    url(r'^coach/profile/$', 'uap_app.views.coach_profile' ),
    url(r'^coach/tickets/$', 'uap_app.views.all_requests_coach' ),
    url(r'^coach/home/$', 'uap_app.views.home_coach'),
    url(r'^coach/ticket_(?P<pid>\d+)$', 'uap_app.views.project_coach' ),
    url(r'^coach/ticket_(?P<pid>\d+)/withdraw/$', 'uap_app.views.coach_withdraw_ticket' ),
    url(r'^coach/submit_meeting_details/ticket_(?P<pid>\d+)$', 'uap_app.views.submit_mtg_details'),
    url(r'^coach/report/$', 'uap_app.views.report_coach'),
    
    #ADMIN
    url(r'^app_admin/home/$', 'uap_app.views.home_admin'),
    url(r'^app_admin/add_new/$', 'uap_app.views.add_new_admin'),
    url(r'^app_admin/coach_requests/$', 'uap_app.views.admin_coach_requests'),
    url(r'^app_admin/coach_request_(?P<pid>\d+)/accept/$', 'uap_app.views.add_coach'),
    url(r'^app_admin/coach_request_(?P<pid>\d+)/reject/$', 'uap_app.views.reject_coach_req'),
    url(r'^app_admin/project/details$', 'uap_app.views.project_details_admin' ),
    url(r'^app_admin/view_tickets/$', 'uap_app.views.admin_view_requests'),
    url(r'^app_admin/view_tutees/$', 'uap_app.views.admin_all_tutee'),
    url(r'^app_admin/view_coaches/$', 'uap_app.views.admin_all_coach'),
    url(r'^app_admin/view_coach(?P<pid>\d+)/$', 'uap_app.views.admin_view_coach'),
    url(r'^app_admin/view_coach(?P<pid>\d+)/hours/$', 'uap_app.views.view_coach_hours'),
    url(r'^app_admin/assign_request_(?P<pid>\d+)$', 'uap_app.views.assign_coach'),
    url(r'^app_admin/ticket_(?P<pid>\d+)$', 'uap_app.views.admin_view_request' ),
    url(r'^app_admin/ticket_(?P<pid>\d+)/assign/$', 'uap_app.views.assign_ticket' ),
    url(r'^app_admin/ticket_(?P<pid>\d+)/approve/$', 'uap_app.views.admin_approve_ticket' ),
    url(r'^app_admin/ticket_(?P<pid>\d+)/reject/$', 'uap_app.views.admin_reject_ticket' ),
    url(r'^app_admin/profile/$', 'uap_app.views.admin_profile' ),
    
    
    
   #   url(r'^pennypincher/$', 'pennypincher_test.views.home'),
#      url(r'^pennypincher/home/$', 'pennypincher_test.views.home'),
 #     url(r'^pennypincher/homer/$', 'pennypincher_test.views.homer'),
  #    url(r'^pennypincher/summary/$', 'pennypincher_test.views.summary'),
   #   url(r'^pennypincher/summary/(?P<detail_username>[a-zA-Z0-9]+)$', 'pennypincher_test.views.detail'), #test this page*****
    #  url(r'^pennypincher/settings$', 'pennypincher_test.views.settings'),
)

uap_app/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User, Permission
from django.forms.extras.widgets import *
from datetime import *
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import Group

  
## CHOICES 
SIX1 = '6-1'
SIX2 = '6-2'
SIX3 = '6-3'
SIX7 = '6-7'
COURSE_CHOICES = (
    (SIX1, '6-1: Electrical Engineering'),
    (SIX2, '6-2: Electrical Engineering & Computer Science'),
    (SIX3, '6-3: Computer Science and Engineering'),
    (SIX7, '6-7: Computer Science and Molecular Biology')
)   
OPEN = 'OP'
ACCEPTED = 'AC'
REJECTED = 'RJ'
COACH_APP_STATUS_CHOICES = (
    (OPEN, 'Open Request'),
    (ACCEPTED, 'Accepted'),
    (REJECTED, 'Rejected'),
)
SEMESTER_CHOICES = (
    ('SP', 'Spring'),
    ('FL', 'Fall'),
    ('NA', 'N/A')     #if not yet taken
) 
 
STATUS_CHOICES = (
    ('NAS', 'Needs Coach Assignment'),
    ('CAS', 'Coach Assigned'),
    ('CSB', 'Coach Submit Ticket'),
    ('TCF', 'Tutee Confirms Ticket'),
    ('APR', 'Admin Approval of Ticket'),
    ('NAP', 'Admin Denies Approval'),
    ('CNL', 'Cancelled Ticket')
)

class CoachRequest(models.Model):
    first_name = models.CharField(max_length=16)
    last_name = models.CharField(max_length=16)
    athena = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    course = models.CharField(max_length=3, choices=COURSE_CHOICES)
    status = models.CharField(max_length=2, choices=COACH_APP_STATUS_CHOICES, default=OPEN)
    uat_semester = models.CharField(max_length=3, choices=SEMESTER_CHOICES)
    uat_year = models.IntegerField(max_length=4)
    
        
class CoachUser(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=11)
    course = models.CharField(max_length=3, choices=COURSE_CHOICES)
    projects_assigned = models.IntegerField(default = 0)
    
    def __string__(self):
        print self.user.username + ', Coach'
    
class TuteeUser(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=11)
    research_advisor = models.TextField()
    research_advisor_email = models.TextField()
    open_project = models.BooleanField()
    def __string__(self):
        print self.user.username + ', Tutee'
    
class AdminUser(models.Model):
    user = models.OneToOneField(User)
    
    def __string__(self):
        print self.user.username + ', Admin'


"""
Let the following integers represent the status of the Project:
** did not want to created static choices bc not sure how these will change **

1 = just initiated by TuteeUser --> AdminUser needs to assign
2 = AdminUser has assigned and awaits "acceptance" --> CoachUser needs to accept
3 = CoachUser accepts assigment
4 = CoachUser submits completion, video file uploaded
5 = TuteeUser confirms meeting
6 = AdminUser approves and "closes" the project

7 = CoachUser rejects an assignment --> AdminUser needs to reassign
8 = TuteeUser cancels the project

"""


class Ticket(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    area_of_interest = models.CharField(max_length=30)
    date_of_interest = models.DateField(null=True)   #ie. presentation date, date of defense, etc.
    date_created = models.DateField(auto_now_add=True) #date ticket created by tutee
    status = models.CharField(max_length = 3, choices = STATUS_CHOICES) 
    tutee = models.ForeignKey(TuteeUser)
    coach = models.ForeignKey(CoachUser, null=True)
    def __string__(self):
        print 'created by ' + self.tutee.user.username
    
class TicketDetails(models.Model):
    # video = models.FileField(upload_to='video/', null=True)   --- NOW WITH TicketVideo
    meeting_details = models.TextField(blank=True)      
    meeting_duration = models.IntegerField(default = 0) # length of meeting time in minutes
    meeting_date = models.DateField(null=True)      # date that the coach/tutee meeting occurred
    ticket = models.OneToOneField(Ticket)
        
class TicketVideo(models.Model):
    video = models.FileField(upload_to='video/')
    ticket = models.OneToOneField(Ticket)

class TicketVideoURL(models.Model):
    video_url = models.CharField(max_length=100)
    ticket = models.OneToOneField(Ticket)

class TicketNote(models.Model):
    ticket = models.ForeignKey(Ticket)
    details = models.TextField(blank=True)
    coach = models.ForeignKey(CoachUser)
        
class TicketForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput({ "placeholder": "Project Talk on K-lines" }), label = "Conference Talk Title")
    details = forms.CharField(widget=forms.Textarea, label="Paper Abstract (optional)", required = False)
    date_of_interest = forms.DateField(widget=forms.TextInput({ "placeholder": "YYYY-MM-DD" }), label="Approximate Conference Presentation Date")
    area_of_interest = forms.CharField(widget=forms.TextInput({ "placeholder": "ie. Artificial Intelligence" }))
    
class TicketDetailsForm(forms.Form):
    #video = forms.FileField(required = False) ##FOR NOW MUST CHANGE!!
    meeting_details = forms.CharField(widget=forms.Textarea)
    meeting_duration = forms.IntegerField(label = "Duration of Meeting (mins)", widget=forms.TextInput({ "placeholder": "ex: 1 Hour = '60'" }))
    meeting_date = forms.DateField()    

class TicketVideoForm(forms.Form):
    vid_file = forms.FileField(required = False, label="Video File")
    vid_url = forms.URLField(required = False, label="Video URL", widget=forms.TextInput({ "placeholder": "www.youtube.com/my_video1173" }))

class TicketNoteForm(forms.Form):
    details = forms.CharField(widget=forms.Textarea, label='Reason for Withdrawl')
   
class TuteeUserForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput({ "placeholder": "jsmith2013" }), label="Userame (Athena)")
    password = forms.CharField(widget=forms.TextInput({ "placeholder": "password123" }))
    first_name = forms.CharField(widget=forms.TextInput({ "placeholder": "Jane" }))
    last_name = forms.CharField(widget=forms.TextInput({ "placeholder": "Smith" }))
    phone = forms.CharField(max_length=11, widget=forms.TextInput({ "placeholder": "18005556789" }))
    research_advisor_email = forms.EmailField(widget=forms.TextInput({ "placeholder": "johndoe@mit.edu" }))
    
class AdminUserForm(forms.Form):
    username =  forms.CharField()
    password = forms.CharField()
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    
class AdminUserProfileForm(forms.Form):
    email = forms.EmailField()
    
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class EmailAdminForm(forms.Form):
    subject = forms.CharField(label="Subject")
    message = forms.CharField(widget = forms.Textarea, label="Problem Description")
    
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.CharField()
    subject = forms.CharField(label="Subject")
    message = forms.CharField(widget = forms.Textarea, label="Message")

class CoachReqForm(forms.Form):
    athena_username = forms.CharField(widget=forms.TextInput({ "placeholder": "jsmith2013" })) 
    first_name = forms.CharField(widget=forms.TextInput({ "placeholder": "Jane" }))
    last_name = forms.CharField(widget=forms.TextInput({ "placeholder": "Smith" }))  
    phone = forms.CharField(widget=forms.TextInput({ "placeholder": "15005552358" }))
    course = forms.ChoiceField(choices = COURSE_CHOICES)
    uat_semester = forms.ChoiceField(widget=forms.Select, choices = SEMESTER_CHOICES, label="Semester enrolled in 6.UAT")
    uat_year = forms.IntegerField(label="Year enrolled in 6.UAT", widget=forms.TextInput({ "placeholder": "2012" }))

class ChangePasswordForm(forms.Form):
    current = forms.CharField(label="Current Password") 
    new1 = forms.CharField(widget=forms.PasswordInput(render_value=False), label="New Password")
    new2 = forms.CharField(widget=forms.PasswordInput(render_value=False), label="Confirm New Password")

class ValidateAgreementForm(forms.Form):
    agree = forms.BooleanField(required=True, label="I have read and agree with the terms and conditions outlined above")
    
class NewAdminForm(forms.Form):
    username = forms.CharField(label="Athena Username")
    first_name = forms.CharField()
    last_name = forms.CharField()

templates/base_test.html
<!DOCTYPE html>
<html>
<head>
<title>Course 6 Communications Center</title>
	<link rel="stylesheet" href="{{STATIC_URL}}blueprint/print.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{STATIC_URL}}blueprint/screen_test.css" type="text/css" media="screen" />
<style type="text/css">

.login label {
    width:150px;
    margin-top: 3px;
    display:inline-block;
    float:left;
    padding:3px;
}
.login input {
    height:20px;
    padding:5px 8px;
	width: 165px;
}

.login input, .login textarea {
    border:1px solid #aaa;
    border-radius:2px;
}
.login input:focus, .contact_form textarea:focus {
    background: #fff;
    border:1px solid #555;
    box-shadow: 0 0 3px #aaa;
}
/* Button Style */
button.submit {
	margin-left: auto;
	margin-right: auto;
	width: 200px;
    background-color: #68b12f;
    background: -webkit-gradient(linear, left top, left bottom, from(#68b12f), to(#50911e));
    background: -webkit-linear-gradient(top, #68b12f, #50911e);
    background: -moz-linear-gradient(top, #68b12f, #50911e);
    background: -ms-linear-gradient(top, #68b12f, #50911e);
    background: -o-linear-gradient(top, #68b12f, #50911e);
    background: linear-gradient(top, #68b12f, #50911e);
    border: 1px solid #509111;
    border-bottom: 1px solid #5b992b;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    -ms-border-radius: 3px;
    -o-border-radius: 3px;
    box-shadow: inset 0 1px 0 0 #9fd574;
    -webkit-box-shadow: 0 1px 0 0 #9fd574 inset ;
    -moz-box-shadow: 0 1px 0 0 #9fd574 inset;
    -ms-box-shadow: 0 1px 0 0 #9fd574 inset;
    -o-box-shadow: 0 1px 0 0 #9fd574 inset;
    color: white;
    font-weight: bold;
    padding: 6px 20px;
    text-align: center;
    text-shadow: 0 -1px 0 #396715;
}
button.submit:hover {
    opacity:.85;
    cursor: pointer;
}
button.submit:active {
    border: 1px solid #20911e;
    box-shadow: 0 0 10px 5px #356b0b inset;
    -webkit-box-shadow:0 0 10px 5px #356b0b inset ;
    -moz-box-shadow: 0 0 10px 5px #356b0b inset;
    -ms-box-shadow: 0 0 10px 5px #356b0b inset;
    -o-box-shadow: 0 0 10px 5px #356b0b inset;
}
.pdding {
	padding: 20px;
}

.center {
	float: none;
	display: block;
	margin: 0px auto;
}

#id_subject {
	width: 380px;
}

body {background-color:#F9F5F1; 
	background-image: url("{{STATIC_URL}}images/header.png"); 
	background-repeat: repeat-x;
	margin-left: auto;
	margin-right: auto;}
.menu ul
{
	position: relative;
	top: 29px;
list-style-type:none;
margin:0;
padding:0;
overflow:hidden;
}
.menu li
{
float:right;
}
.menu a
{
display:block;
width:110px;
height: 30px;
background-color:#dddddd;
background: rgb(24, 24, 24) transparent; /* default fallback */
background: rgba(24, 24, 24, 0.05); /* nice browsers */
text-decoration: none;
display: table-cell;
vertical-align: middle;
color: black;
}

.menu a:hover {
	background: rgb(150, 21, 21) transparent; /* default fallback */
	background: rgba(150, 21, 21, 0.6); /* nice browsers */	
	color: white;
}

.selected a{
	background-color: #961515;
	color: white;
}

#content
{
position: absolute;
top: 115px;
min-height: 500px;
background-color: ;
}
.menu {
	height: 90px;
	color: black;
	text-align: center;
}
#homeicon {
	position: relative;
	top: 20px;
}

.example1 {
-moz-border-radius: 15px;
border-radius: 15px;
border: 1px solid;
border-color: DarkGray;
background-color: WhiteSmoke;
background: rgb(24, 24, 24) transparent; /* default fallback */
background: rgba(24, 24, 24, 0.05); /* nice browsers */
}

#name_text{
	position: relative;
	top: 20px;
	align: right;
}

input:-moz-placeholder {
    color: gray;
}
input::-webkit-input-placeholder {
    color: gray;
}
{% block scripts %}{% endblock %}
</style>

<script type="text/javascript">
{% block js %}{% endblock %}
</script>

</head>

<body>

<div class="container">	
<div class="column span-24">
	<div class = "menu column span-7 ">
		<img id="homeicon" src="{{STATIC_URL}}images/cscc.png"/>
	</div>
	<div class="span-17 last">
		<div align="right" id="name_text"class="span-17 last">
			<p><b>TUTEE | {{user.username}}</b>, {{user.first_name}} {{user.last_name}}</p>
		</div>
	<div class="menu  span-17">
		<ul>
			<li {% block logout %}{% endblock %}><a href="/logout">LOGOUT</a></li>
			<li {% block profile %}{% endblock %}><a href="/tutee/profile/">PASSWORD</a></li>
			<li {% block report %}{% endblock %}><a href="/tutee/report/">REPORT</a></li>
			<li {% block tickets %}{% endblock %}><a href="/tutee/tickets/">TICKETS</a></li>
			<li {% block home %}{% endblock %}><a href="/tutee/home">HOME</a></li>
		</ul>
	</div>
	</div>
</div>
	<div id="content" class="column span-24 last">
		{% block content %}
		{% endblock %}
	</div>
</div>
</body>

</html>

templates/basecase.html
<!DOCTYPE html>
<html>
<head>
<title>Course 6 Communications Center</title>
	<link rel="stylesheet" href="{{STATIC_URL}}blueprint/print.css" type="text/css" media="screen" />
	<link rel="stylesheet" href="{{STATIC_URL}}blueprint/screen_test.css" type="text/css" media="screen" />
<style type="text/css">
{% block scripts %}
{% endblock %}

.login label {
    width:150px;
    margin-top: 3px;
    display:inline-block;
    float:left;
    padding:3px;
}
.login input {
    height:20px;
    padding:5px 8px;
	width: 165px;
}

.login input, .login textarea {
    border:1px solid #aaa;
    border-radius:2px;
}
.login input:focus, .contact_form textarea:focus {
    background: #fff;
    border:1px solid #555;
    box-shadow: 0 0 3px #aaa;
}
/* Button Style */
button.submit {
	margin-left: auto;
	margin-right: auto;
	width: 200px;
    background-color: #68b12f;
    background: -webkit-gradient(linear, left top, left bottom, from(#68b12f), to(#50911e));
    background: -webkit-linear-gradient(top, #68b12f, #50911e);
    background: -moz-linear-gradient(top, #68b12f, #50911e);
    background: -ms-linear-gradient(top, #68b12f, #50911e);
    background: -o-linear-gradient(top, #68b12f, #50911e);
    background: linear-gradient(top, #68b12f, #50911e);
    border: 1px solid #509111;
    border-bottom: 1px solid #5b992b;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    -ms-border-radius: 3px;
    -o-border-radius: 3px;
    box-shadow: inset 0 1px 0 0 #9fd574;
    -webkit-box-shadow: 0 1px 0 0 #9fd574 inset ;
    -moz-box-shadow: 0 1px 0 0 #9fd574 inset;
    -ms-box-shadow: 0 1px 0 0 #9fd574 inset;
    -o-box-shadow: 0 1px 0 0 #9fd574 inset;
    color: white;
    font-weight: bold;
    padding: 6px 20px;
    text-align: center;
    text-shadow: 0 -1px 0 #396715;
}
button.submit:hover {
    opacity:.85;
    cursor: pointer;
}
button.submit:active {
    border: 1px solid #20911e;
    box-shadow: 0 0 10px 5px #356b0b inset;
    -webkit-box-shadow:0 0 10px 5px #356b0b inset ;
    -moz-box-shadow: 0 0 10px 5px #356b0b inset;
    -ms-box-shadow: 0 0 10px 5px #356b0b inset;
    -o-box-shadow: 0 0 10px 5px #356b0b inset;
}
.pdding {
	padding: 20px;
}

.center {
	float: none;
	display: block;
	margin: 0px auto;
}

#id_subject {
	width: 380px;
}

body {background-color:#F9F5F1; 
	background-image: url("{{STATIC_URL}}images/header.png"); 
	background-repeat: repeat-x;
	margin-left: auto;
	margin-right: auto;}
.menu ul
{
	position: relative;
	top: 65px;
list-style-type:none;
margin:0;
padding:0;
overflow:hidden;
}
.menu li
{
float:right;
}
.menu a
{
display:block;
width:120px;
height: 30px;
background-color:#dddddd;
background: rgb(24, 24, 24) transparent; /* default fallback */
background: rgba(24, 24, 24, 0.05); /* nice browsers */
text-decoration: none;
display: table-cell;
vertical-align: middle;
color: black;
}

.menu a:hover {
	background: rgb(150, 21, 21) transparent; /* default fallback */
	background: rgba(150, 21, 21, 0.6); /* nice browsers */	
	color: white;
}

.selected a{
	background-color: #961515;
	color: white;
}

#content
{
position: absolute;
top: 115px;
min-height: 500px;
background-color: ;
}
.menu {
	height: 90px;
	color: black;
	text-align: center;
}
#homeicon {
	position: relative;
	top: 20px;
}

.example1 {
-moz-border-radius: 15px;
border-radius: 15px;
border: 1px solid;
border-color: DarkGray;
background-color: WhiteSmoke;
background: rgb(24, 24, 24) transparent; /* default fallback */
background: rgba(24, 24, 24, 0.05); /* nice browsers */
}

input:-moz-placeholder {
    color: gray;
}
input::-webkit-input-placeholder {
    color: gray;
}

</style>

</head>

<body>

<div class="container">	
<div class="column span-24">
	<div class = "menu column span-7 ">
		<img id="homeicon" src="{{STATIC_URL}}images/cscc.png"/>
	</div>
	<div class="menu column span-17 last">
		<ul>
			<li {% block contact %}{% endblock %}><a href="/contact/">CONTACT</a></li>
			<li {% block login %}{% endblock %}><a href="/accounts/login">LOGIN</a></li>
			<li {% block signup %}{% endblock %}><a href="/tutee/signup/">SIGN UP</a></li>
			<li {% block home %}{% endblock %}><a href="/">HOME</a></li>
		</ul>
	</div>
</div>
	<div id="content" class="column span-24 last">
		{% block content %}
		{% endblock %}
	</div>
</div>
</body>

</html>

templates/report_coach.html
{% extends "base_coach.html" %}


{% block scripts %}

.login label {
    width:150px;
    margin-top: 3px;
    display:inline-block;
    float:left;
    padding:3px;
}
.login input {
    height:20px;
    padding:5px 8px;
	width: 165px;
}

.login input, .login textarea {
    border:1px solid #aaa;
    border-radius:2px;
}
.login input:focus, .contact_form textarea:focus {
    background: #fff;
    border:1px solid #555;
    box-shadow: 0 0 3px #aaa;
}
/* Button Style */
button.submit {
	margin-left: auto;
	margin-right: auto;
	width: 200px;
    background-color: #68b12f;
    background: -webkit-gradient(linear, left top, left bottom, from(#68b12f), to(#50911e));
    background: -webkit-linear-gradient(top, #68b12f, #50911e);
    background: -moz-linear-gradient(top, #68b12f, #50911e);
    background: -ms-linear-gradient(top, #68b12f, #50911e);
    background: -o-linear-gradient(top, #68b12f, #50911e);
    background: linear-gradient(top, #68b12f, #50911e);
    border: 1px solid #509111;
    border-bottom: 1px solid #5b992b;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    -ms-border-radius: 3px;
    -o-border-radius: 3px;
    box-shadow: inset 0 1px 0 0 #9fd574;
    -webkit-box-shadow: 0 1px 0 0 #9fd574 inset ;
    -moz-box-shadow: 0 1px 0 0 #9fd574 inset;
    -ms-box-shadow: 0 1px 0 0 #9fd574 inset;
    -o-box-shadow: 0 1px 0 0 #9fd574 inset;
    color: white;
    font-weight: bold;
    padding: 6px 20px;
    text-align: center;
    text-shadow: 0 -1px 0 #396715;
}
button.submit:hover {
    opacity:.85;
    cursor: pointer;
}
button.submit:active {
    border: 1px solid #20911e;
    box-shadow: 0 0 10px 5px #356b0b inset;
    -webkit-box-shadow:0 0 10px 5px #356b0b inset ;
    -moz-box-shadow: 0 0 10px 5px #356b0b inset;
    -ms-box-shadow: 0 0 10px 5px #356b0b inset;
    -o-box-shadow: 0 0 10px 5px #356b0b inset;
}
.pdding {
	padding: 20px;
}

#id_subject {
	width: 380px;
}

{% endblock %}

{%block report%}class="selected"{% endblock %}

{% block content %}
<div class="container">
	<div class="span-3"><p></p></div>
<div class="example1 pdding prepend-top span-17 last append-bottom">
	<h1> <b> report problem </b></h1>
	<p> We are sorry that you have encountered a problem; please be as detailed as possible to help us understand the issue.
	<form class="login" action="" method="POST">
		{% csrf_token %}
	{{form.as_p}}
	<button id="submit" class="submit center span-4" type="submit" value="submit">SUBMIT REPORT </button>
	</form>
</div>
<div class="span-4"><p></p></div>
</div>
{% endblock %}